path: C:/Users/Malv/Downloads/class/ai_lab/ai_course/uas #root
train: yolo_dataset/train/images #training
val: yolo_dataset/valid/images #validity
test: yolo_dataset/test/images #testing

# classes
names: 
- device
- live
- mask
- photo

roboflow:
  workspace: zongrui-liu
  project: face-nni0m
  version: 5
  license: CC BY 4.0
  url: https://universe.roboflow.com/zongrui-liu/face-nni0m/dataset/5